name: GitHub Classroom Workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    name: Autograding
    runs-on: ubuntu-latest

    permissions:
      contents: read

    defaults:
      run:
        shell: bash --noprofile --norc -Eeuxo pipefail {0}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image (builder stage)
        uses: docker/build-push-action@v6
        with:
          context: .
          target: unit-tests
          load: true
          tags: unittests:latest

      - name: Run pytest tests
        run: |
          docker run --rm unittests:latest

      - name: Build Docker image (production stage)
        run: |
          docker compose build

      - name: Run services
        run: |
          docker compose up --detach

      - name: Wait for services to start
        timeout-minutes: 5
        run: |
          ./scripts/wait-script.sh
        env:
          WAIT_PORTS: 8080,8070,8060,8050

      - name: Setup Node.js
        uses: actions/setup-node@v4

      - name: Install Newman
        run: npm install -g newman

      - name: Run API Tests
        timeout-minutes: 5
        run: ./scripts/test-script.sh
        env:
          VARIANT: v4
          SERVICE_NAME: rating_service
          PORT_NUMBER: 8050

      - name: Stop containers
        if: always()
        continue-on-error: true
        run: docker compose down --volumes